[microsoft-edge-stable]
source = "rpmrepo"
repo = "https://packages.microsoft.com/yumrepos/edge"
pkg = "microsoft-edge-stable"
arch = "x86_64"

[visual-studio-code]
source = "cmd"
cmd = "curl -s 'https://update.code.visualstudio.com/api/update/linux-x64/stable/latest' | jq -r '.productVersion'"

[qt-sudo]
source = "github"
github = "aarnt/qt-sudo"
use_latest_release = true
prefix = "v"

[octopi]
source = "github"
github = "aarnt/octopi"
use_latest_release = true
prefix = "v"

# [ntfsprogs-plus]
# source = "github"
# github = "ntfsprogs-plus/ntfsprogs-plus"
# use_latest_release = true

# [antigravity-cli]
# source = "github"
# github = "google-antigravity/antigravity-cli"
# use_latest_release = true

#[anytype]
#source = "github"
#github = "anyproto/anytype-ts"
#use_max_tag = true
#prefix = "v"
#include_regex = '^0\.\d+\.\d+$'

# [lm-studio-version]
# source = "regex"
# url = "https://lmstudio.ai/download"
# regex = '\\"linux\\":\{\\"x64\\":\{\\"version\\":\\"([\d\.]+)\\"'

# [lm-studio-build]
# source = "regex"
# url = "https://lmstudio.ai/download"
# regex = '\\"linux\\":\{\\"x64\\":\{\\"version\\":\\"[0-9.]+\\",\\"build\\":\\"([0-9]+)\\"'

# [lm-studio]
# source = "combiner"
# from = ["lm-studio-version", "lm-studio-build"]
# format = "$1.$2"
