# Colored makepkg-like functions
msg_blue() {
    printf "${blue}==>${bold} $1${all_off}\n"
}

note() {
    printf "${blue}==>${yellow} NOTE:${bold} $1${all_off}\n"
}

all_off="$(tput sgr0)"
bold="${all_off}$(tput bold)"
blue="${bold}$(tput setaf 4)"
yellow="${bold}$(tput setaf 3)"

post_install() {
    note "Custom flags should be put directly in: ~/.config/code-flags.conf"
    
    # Create symlink for cliPath expected by VS Code when performing elevated operations (pkexec Save as Root)
    mkdir -p /usr/lib/electron/bin
    ln -sf /usr/bin/code /usr/lib/electron/bin/code
}

post_upgrade() {
    post_install
}

post_remove() {
    rm -f /usr/lib/electron/bin/code
}