name: Periodic Cleanup
on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Delete old workflow runs
        uses: actions/github-script@v8
        with:
          script: |
            const script = require('./.github/scripts/cleanup-runs.js');
            await script({ github, context });